export const policies = [
  {
    title: "GST",
    link:"GST",
    policy_name: "Goods and Services Tax",
    icon: "https://cdn0.iconfinder.com/data/icons/finance-and-politics-1-1/128/gst_exemption_save_tax-512.png",
    iconBg: "#383E56",
    date: "July 2017 - ...",
    points: [
      "Goods and Services Tax (GST) is a comprehensive indirect tax levied on supply of goods and services in India.",
      "GST subsumed 17 central and state indirect taxes, including excise duty, service tax, VAT, and octroi.",
      "GST is a destination-based tax, which means that the tax is levied at the point of consumption of goods and services.",
      "GST is a single tax, which means that there is no cascading effect of taxes.",
    ],
  },
  {
    title: "Demonetisation",
    link:"Demonetisation",
    policy_name: "Demonetisation-2016",
    icon: "https://www.pngfind.com/pngs/m/643-6433701_indian-money-logo-png-slogans-on-demonetisation-in.png",
    iconBg: "#E6DEDD",
    date: "Nov 2016 - Dec 2016",
    points: [
      "Demonetisation was the act of withdrawing 500 and 1000 rupee notes from circulation in India on 8 November 2016.",
      "The stated aim of demonetisation was to curb corruption, counterfeit currency, and terrorism.",
      "Demonetisation caused widespread disruption and inconvenience, and its economic impact is still being debated.",
      "Demonetisation was a controversial move, and its legacy is likely to be debated for many years to come.",
    ],
  },
  {
    title: "Make in India",
    link:"MakeInIndia",
    policy_name: "Make In India Scheme",
    icon: "https://static.vecteezy.com/system/resources/previews/020/190/685/original/make-in-india-logo-make-in-india-icon-free-free-vector.jpg",
    iconBg: "#383E56",
    date: "Sept 2014 - ....",
    points: [
      "Make in India is a national manufacturing program launched by the Government of India in 2014.",
      "The program aims to attract foreign direct investment (FDI) and boost domestic manufacturing in India.",
      "Make in India has identified 25 sectors for focus, including automobiles, electronics, and pharmaceuticals.",
      "The program has been successful in attracting FDI, and has helped to create jobs and boost economic growth in India.",
    ],
  },
  {
    title: "StartUp India",
    link:"StartupScheme",
    policy_name: "Startup India Scheme",
    icon: "https://d1whtlypfis84e.cloudfront.net/guides/wp-content/uploads/2019/01/15125523/startup-india-scheme-1024x570.jpg",
    iconBg: "#E6DEDD",
    date: "Jan 2016 - ....",
    points: [
      "Startup India is a government initiative launched in 2016 to encourage entrepreneurship and innovation in India.",
      "The program provides a range of support measures to startups, including tax breaks, funding, and mentorship.",
      "Startup India has been successful in attracting a large number of startups, and has helped to create a vibrant startup ecosystem in India.",
      "The program has been praised by entrepreneurs and investors alike, and is seen as a major step towards making India a global hub for innovation.",
    ],
  },
  {
    title: "Swach Bharat Abhiyan",
    link:"SwachBharat",
    policy_name: "Swach Bharat Abhiyan",
    icon: "https://image.winudf.com/v2/image1/Y29tLm1haGVrbXNoYWguc3dhY2hoYmhhcmF0X2ljb25fMTU1MDIyMDgzMF8wNzk/icon.png?w=&fakeurl=1",
    iconBg: "#E6DEDD",
    date: "Oct 2014 - ....",
    points: [
      "Swachh Bharat Abhiyan is a national cleanliness campaign launched by the Government of India in 2014.",
      "The campaign aims to make India a clean and open defecation-free country by 2019.",
      "The campaign has been successful in mobilizing people and resources, and has helped to improve cleanliness in India.",
      "The campaign has been praised by both domestic and international observers, and is seen as a major step towards making India a clean and healthy country.",
    ],
  },
];